version: '2'
services:
  cron:
    build: ./cron
  cli:
    build: ./cli
  fpm:
    build: ./fpm
    user: docker
    volumes:
      - .:/var/www/html
  nginx:
    build: ./nginx
    volumes:
      - .:/var/www/html
    links:
      - fpm
    ports:
      - 8080:80
  varnish:
    build: ./varnish
    ports:
      - 8092:80
  node:
    build: ./node
    user: docker
    volumes:
      - .:/home/docker/app
